auth:
  users:
    - username: admin
      password: admin123
    - username: alice
      password: alice123

flask:
  secret_key: "change_this_to_a_random_secret_in_prod"
upload:
  folder: uploads
  allowed_extensions: ["xls", "xlsx"]
